# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import drugquery.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Docking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_score', models.DecimalField(decimal_places=5, max_digits=8)),
                ('docking_file', models.FilePathField(path='/Users/Nico/Desktop/drugquery_dev/data/dockings/')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugquery.Compound')),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(max_length=50)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugquery.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket_number', models.IntegerField()),
                ('pocket_file', models.FilePathField(path='/Users/Nico/Desktop/drugquery_dev/data/pockets/')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(max_length=50)),
                ('target_file', models.FilePathField(path='/Users/Nico/Desktop/drugquery_dev/data/targets/')),
                ('pdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugquery.Pdb')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='', validators=[drugquery.validators.validate_upload_format])),
            ],
        ),
        migrations.AddField(
            model_name='pocket',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugquery.Target'),
        ),
        migrations.AddField(
            model_name='docking',
            name='pocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugquery.Pocket'),
        ),
    ]
