# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='compound_dir',
            field=models.CharField(default='#', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compound',
            name='compound_file',
            field=models.CharField(default='#', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compound',
            name='compound_img',
            field=models.CharField(default='#', max_length=500),
            preserve_default=False,
        ),
    ]
