# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 18:22
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import drugquery.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0002_auto_20170822_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='compound_dir',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='compound_file',
        ),
        migrations.RemoveField(
            model_name='compound',
            name='compound_img',
        ),
        migrations.AddField(
            model_name='compound',
            name='compound_img_file',
            field=models.FileField(default='#', storage=django.core.files.storage.FileSystemStorage(location='/data/images'), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compound',
            name='compound_smi_file',
            field=models.FileField(default='#', storage=django.core.files.storage.FileSystemStorage(location='/data/compounds'), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/data/uploads'), upload_to='', validators=[drugquery.validators.validate_upload_format]),
        ),
    ]
