# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import drugquery.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0003_auto_20170822_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(upload_to='data/uploads', validators=[drugquery.validators.validate_upload_format]),
        ),
    ]
