# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import drugquery.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0004_auto_20170823_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='compound_img_file',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='compound',
            name='compound_smi_file',
            field=models.FileField(upload_to='compounds'),
        ),
        migrations.AlterField(
            model_name='docking',
            name='docking_file',
            field=models.FilePathField(path='poooopdockings/'),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='pocket_file',
            field=models.FilePathField(path='pooooppockets/'),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_file',
            field=models.FilePathField(path='pooooptargets/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(upload_to='uploads', validators=[drugquery.validators.validate_upload_format]),
        ),
    ]
