# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0005_auto_20170823_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='smiles',
            field=models.CharField(default='#', max_length=500),
            preserve_default=False,
        ),
    ]
