# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import drugquery.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0006_upload_smiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='gene_name',
        ),
        migrations.AddField(
            model_name='gene',
            name='name',
            field=models.CharField(default='#', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdb',
            name='pdb_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(upload_to='', validators=[drugquery.validators.validate_upload_format]),
        ),
    ]
