# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import drugquery.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0007_auto_20170825_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(upload_to='uploads', validators=[drugquery.validators.validate_upload_format]),
        ),
    ]
