# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0008_auto_20170825_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='compound_smi_file',
        ),
        migrations.AddField(
            model_name='compound',
            name='compound_sdf_file',
            field=models.FileField(default='#', upload_to='compounds'),
            preserve_default=False,
        ),
    ]
