# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0010_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Q', 'Queued'), ('R', 'Running'), ('C', 'Complete'), ('E', 'Error')], default='Q', max_length=1),
        ),
    ]
