# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0011_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdb',
            name='name',
            field=models.CharField(default='#', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pocket',
            name='name',
            field=models.CharField(default='#', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='name',
            field=models.CharField(default='#', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pocket',
            name='pocket_file',
            field=models.FileField(upload_to='pockets'),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_file',
            field=models.FileField(upload_to='targets'),
        ),
    ]
