# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0012_auto_20170907_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='name',
            field=models.CharField(default='#', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(default='#', max_length=500),
            preserve_default=False,
        ),
    ]
