# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0013_auto_20170908_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compound',
            name='name',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='name',
        ),
    ]
