# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0015_auto_20170914_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='score_file',
            field=models.FileField(default='#', upload_to='scores'),
            preserve_default=False,
        ),
    ]
