# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import drugquery.validators


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0016_compound_score_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_file',
            field=models.FileField(upload_to='uploads', validators=[drugquery.validators.validate_upload_size, drugquery.validators.validate_upload_format]),
        ),
    ]
