# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0018_auto_20180216_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pdb',
            name='name',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='pdb',
            name='pdb_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='name',
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name='target',
            name='chain',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=42),
        ),
    ]
