# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0019_auto_20180216_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='num_docked_genes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compound',
            name='num_docked_pdbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compound',
            name='num_docked_pockets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compound',
            name='num_docked_targets',
            field=models.IntegerField(default=0),
        ),
    ]
