# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0020_auto_20180216_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='best_docking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='drugquery.Docking'),
        ),
        migrations.AddField(
            model_name='compound',
            name='best_gene',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugquery.Gene'),
        ),
        migrations.AddField(
            model_name='compound',
            name='best_pdb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugquery.Pdb'),
        ),
        migrations.AddField(
            model_name='compound',
            name='best_pocket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugquery.Pocket'),
        ),
        migrations.AddField(
            model_name='compound',
            name='best_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugquery.Target'),
        ),
    ]
