# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0021_auto_20180216_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='best_docking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drugquery.Docking'),
        ),
    ]
