# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugquery', '0023_auto_20180219_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
